use_frameworks!

target 'NewsSeconds' do
     pod 'OpenWhisk', :git => 'https://github.com/openwhisk/openwhisk-client-swift.git', :tag => '0.2.2'
     pod 'DropDown'
     pod 'BMSPush'
     pod 'SwiftMessages'
end

target 'NotificationInterceptor' do
end